{% set version = "1.6.0" %}

package:
  name: cis
  version: {{ version }}

source:
  fn: cis-{{ version }}.tar.gz
  url: https://github.com/cedadev/cis/archive/{{ version }}.tar.gz
  sha256: 22e08e9783bfd4b637500c77c7b44864a6f06123ffdebea52c9658dc8458284d

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - matplotlib >=1.2.0
    - netcdf4 >=1.0
    - numpy 1.11.*
    - scipy <1.2.0
    - iris >=1.8.0,<2
    - pyhdf
    - psutil
    - pandas
    - pyhamcrest
  run:
    - python
    - matplotlib >=1.2.0
    - netcdf4 >=1.0
    - {{ pin_compatible('numpy') }}
    - scipy <1.2.0
    - iris >=1.8.0,<2
    - pyhdf
    - psutil
    - pandas

test:
  imports:
    - cis
  commands:
    - cis version
  requires:
    - mock
    - nose
    - pyhamcrest

about:
  home: http://www.cistools.net
  license: LGPL3
  summary: 'Community Inter-comparison Suite'

extra:
  recipe-maintainers:
    - duncanwp
