{% set version = "1.7.4" %}

package:
  name: cis
  version: {{ version }}

source:
  url: https://github.com/cedadev/cis/archive/{{ version }}.tar.gz
  sha256: 1be4fadbb8b79538a4d2062f40f7272408369b89f181f66b3da9b005525c958f

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - matplotlib >=2
    - netcdf4 >=1.0
    - numpy >=1.10
    - scipy
    - iris >=2.0.0
    - pyhdf  # [not win]
    - psutil
    - pandas
    - pyhamcrest
  run:
    - python
    - matplotlib >=2
    - netcdf4 >=1.0
    - {{ pin_compatible('numpy') }}
    - scipy
    - iris >=2.0.0
    - pyhdf  # [not win]
    - psutil
    - pandas

test:
  imports:
    - cis
  commands:
    - cis version
  requires:
    - mock
    - nose
    - pyhamcrest

about:
  home: http://www.cistools.net
  license: LGPL-3.0
  license_file: COPYING
  summary: Community Inter-comparison Suite

extra:
  recipe-maintainers:
    - duncanwp
