{% set version = "1.7.5" %}

package:
  name: cis
  version: {{ version }}

source:
  url: https://github.com/cedadev/cis/archive/{{ version }}.tar.gz
  sha256: ed72194e9a9e8767a787852d3c7762ef8a2ab29a7d23754f1540828cf1ef0406

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - matplotlib >=2
    - netcdf4 >=1.0
    - numpy >=1.10
    - scipy
    - iris >=2.0.0
    - pyhdf  # [not win]
    - psutil
    - pandas
    - pyhamcrest
  run:
    - python
    - matplotlib >=2
    - netcdf4 >=1.0
    - {{ pin_compatible('numpy') }}
    - scipy
    - iris >=2.0.0
    - pyhdf  # [not win]
    - psutil
    - pandas

test:
  imports:
    - cis
  commands:
    - cis version
  requires:
    - mock
    - nose
    - pyhamcrest

about:
  home: http://www.cistools.net
  license: LGPL-3.0
  license_file: COPYING
  summary: Community Inter-comparison Suite

extra:
  recipe-maintainers:
    - duncanwp
