{% set version = "1.6.0_a1" %}

package:
  name: cis
  version: {{ version }}

source:
  fn: cis-{{ version }}.tar.gz
  url: https://github.com/cedadev/cis/archive/{{ version }}.tar.gz
  sha256: 60a628ac282c7358e8c7266f3087d3fd7d9d2bcb5ea5c5a5010a652f7e00eeb8

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - matplotlib >=1.2.0
    - setuptools
    - netcdf4 >=1.0
    - numpy
    - scipy
    - iris >=1.8.0
    - pyhdf
    - psutil
    - pandas
    - pyhamcrest
  run:
    - python
    - matplotlib >=1.2.0
    - netcdf4 >=1.0
    - numpy
    - scipy
    - iris >=1.8.0
    - pyhdf
    - psutil
    - pandas

test:
  imports:
    - cis
  commands:
    - cis version
  requires:
    - mock
    - nose
    - pyhamcrest

about:
  home: http://www.cistools.net
  license: LGPL3
  summary: 'Community Inter-comparison Suite'

extra:
  recipe-maintainers:
    - duncanwp
