{% set version = "1.7.1" %}

package:
  name: cis
  version: {{ version }}

source:
  fn: cis-{{ version }}.tar.gz
  url: https://github.com/cedadev/cis/archive/{{ version }}.tar.gz
  sha256: adb0c5de1b828b1e1e9c1d1b7996ca4a9c7cbf01c8b80987427a5f723a89cc8a

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - matplotlib >=2,<3
    - netcdf4 >=1.0
    - numpy >=1.10,<1.16
    - scipy
    - iris >=2.0.0
    - pyhdf  # [not win]
    - psutil
    - pandas <0.24
    - pyhamcrest
  run:
    - python
    - matplotlib >=2,<3
    - netcdf4 >=1.0
    - {{ pin_compatible('numpy') }}
    - scipy
    - iris >=2.0.0
    - pyhdf  # [not win]
    - psutil
    - pandas <0.24

test:
  imports:
    - cis
  commands:
    - cis version
  requires:
    - mock
    - nose
    - pyhamcrest

about:
  home: http://www.cistools.net
  license: LGPL3
  summary: 'Community Inter-comparison Suite'

extra:
  recipe-maintainers:
    - duncanwp
