{% set version = "1.7.8" %}

package:
  name: cis
  version: {{ version }}

source:
  url: https://github.com/cedadev/cis/archive/{{ version }}.tar.gz
  sha256: ec2dab7186d3728c569953c3afc11651d977da565e974f2bd497f3c140526f41

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - python
    - pip
    - matplotlib >=2
    - netcdf4 >=1.0
    - numpy >=1.10
    - scipy
    - iris >=2.0.0
    - pyhdf  # [not win]
    - psutil
    - pandas
    - pyhamcrest
  run:
    - python
    - matplotlib >=2
    - netcdf4 >=1.0
    - {{ pin_compatible('numpy') }}
    - scipy
    - iris >=2.0.0
    - pyhdf  # [not win]
    - psutil
    - pandas

test:
  imports:
    - cis
  commands:
    - cis version
  requires:
    - mock
    - nose
    - pyhamcrest

about:
  home: http://www.cistools.net
  license: LGPL-3.0
  license_file: COPYING
  summary: Community Inter-comparison Suite

extra:
  recipe-maintainers:
    - duncanwp
