{% set version = "1.7.2" %}

package:
  name: cis
  version: {{ version }}

source:
  url: https://github.com/cedadev/cis/archive/{{ version }}.tar.gz
  sha256: ffd29d7a559a96451766bd18358a11f44b6bebe4564bb7f79cf3affe81c1509d

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - matplotlib >=2,<3
    - netcdf4 >=1.0
    - numpy >=1.10,<1.16
    - scipy
    - iris >=2.0.0
    - pyhdf  # [not win]
    - psutil
    - pandas
    - pyhamcrest
  run:
    - python
    - matplotlib >=2,<3
    - netcdf4 >=1.0
    - {{ pin_compatible('numpy') }}
    - scipy
    - iris >=2.0.0
    - pyhdf  # [not win]
    - psutil
    - pandas

test:
  imports:
    - cis
  commands:
    - cis version
  requires:
    - mock
    - nose
    - pyhamcrest

about:
  home: http://www.cistools.net
  license: LGPL-3.0
  license_file: COPYING
  summary: 'Community Inter-comparison Suite'

extra:
  recipe-maintainers:
    - duncanwp
