travis:
  secure:
    BINSTAR_TOKEN: DYum7FWv6q5Q1mAYlqD2TQ/Lj7a6xJd7GjjR01L25j7DI++hq7FUbgHswoJk+kU9N1fSnbgBHQUzdiJ9KeaAj+mHbJhrsiqJBILTEgAvBPVLQq8pfytr0Qy/1jbCdJz5aCZ9n3cL03W//jTYo2SMo8lzsi2etdNfNtwMh9m7pCJGUzxnWqPWgJ9qOTnDpIfRS1XYsvudOjPo4NtnioCZSwFb+v0KXSk2Nu4SRFykMy4JfEa9RGmIlyuvzCHm5wopz3yQ3RqJrOGAi380MvIBK5huvXqeEvFFpyu5mttW/+zk3la8C+skOr+7iX5lpWe1I5/Kkda5x89jKZ+pLf69cNTMRDOtl/BvU8iubN2Ny/hlu9NB4xgwvVzJ74n5N/dVkHvyXVyEijXXepothiSrgYvVUdDTgBTeRXKx7dpmCF4fZmqdUwI8Ybp5Ak2OpMLRNDVwxD2wITHQ9BHujr+08mdfqWJJ97a9+RpGUtdT3g5u69sc8pqiwVBsLlfb0afh7Tv3d3lgPuNZ+Wr5BVEJcA7MnDG+LilZgxtbJU+IXJgHHURYpCgvGDQifPs8Tm8VVM514Mh7orWRldvAG1LZYKPzDj2KkNKvodcRQabrJZQfYKH1iEAS70MSvl9qNBUSaoMET1O/4OFpNgSLC5SjfX+I5OTrDGQDp4Ud9uzyflU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
