travis:
  secure:
    BINSTAR_TOKEN: hbhUoeYuC3jf14PgMLQvDZcpR6gtSdXv+29ZEJcRro2TiSvNGm3/e5aUEOhnzRAToBgKLU6e590JRxuPKS//g1YeySBVHOMjtRylKfjb0p99aLJ73LfhOfzh1olNxGHEPreca4ruvTQPgHa7QabQV18QphaaR+PtgOhOLUN9tnHdNdLhBQYPmWRfjaLVMj9UvRafJFTyLr78efLTYhaZEt5c67cowQq28Uk3c2ZLpPi39t1VhQZYAkKFMm5EYKcrqlxU58bTD4VysuWnNADaC3LNp7TZeRMNm9kjphqVUsvUyMgwyyI4Z97z8d8X4vyF+S+IBOzN9H5U5szNOdamqahkcdJU99uOtQ9UGzitVvctVN3Z5QnVDr45P+H+5ZmmcDVAw+zGzshQQ4rGbpMTkfz0d0Rs/c9e3o4BWpiGf0NVidO+gWmW0nVg4dIZHSe3S5WHGJKaxzwTRtp3atLlm2QOM6rvWWRLU3Du9aiD8UblNT4jejf5ij5i+yDqgUGTwr8/n/JH6GvdKnMlkhyAcuLC2Cp7Kj4PcsfauGO3u8THxSQTl/HG3otZGPK8NsmB5c49GSGtG1QZsnAPrmSiYFotSF89Q2mF/kQNaEB6zCMRd1oUOEPm1Fb1ZHn+dKUNR7D7VUq5y4jRA+ZBmszN9XJKsAwb6I0j4WNauimdl+w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider:
  win: azure
